### ISSUE TITLE
Next game ignores user-defined images

### ISSUE THREAD

**Issue by banool** [banool/codenames-pictures#20]
When the user specifies a link to their own images, if you press next game the next game will not use the user's images and instead just fall back to the default. It should continue to use the user's images.

**Comment by banool** [comment]
This isn't quite right. It uses the exact same images as the previous game, whereas what we wanted is for it to randomly pick new images from the image source.

**Comment by jackwilsdon** [comment]
Oops! I'll have a look at fixing that tomorrow :smiley:

**Comment by jackwilsdon** [comment]
Ok, #28 should fix it this time 😁🙏
